#!/usr/bin/env python3
"""Select a desktop color scheme and generate native palette adapters."""

from __future__ import annotations

import argparse
import os
import re
import sys
import tempfile
import tomllib
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
THEME_DIR = ROOT / "theme"
SCHEMES_DIR = THEME_DIR / "schemes"
CONFIG_PATH = THEME_DIR / "config.toml"
REQUIRED_COLORS = (
    "surface",
    "surface_secondary",
    "border_muted",
    "text",
    "text_muted",
    "accent",
    "accent_bright",
    "success",
    "warning",
    "error",
    "error_alt",
)
OUTPUT_PATHS = {
    "hypr_lua": ROOT / ".config/hypr/modules/palette_generated.lua",
    "hyprlock": ROOT / ".config/hypr/palette_generated.conf",
    "waybar": ROOT / ".config/waybar/colors.generated.css",
    "swaync": ROOT / ".config/swaync/colors.generated.css",
    "wofi": ROOT / ".config/wofi/colors.generated.css",
}


def load_toml(path: Path) -> dict:
    try:
        with path.open("rb") as file:
            return tomllib.load(file)
    except (OSError, tomllib.TOMLDecodeError) as error:
        raise ValueError(f"cannot read {path.relative_to(ROOT)}: {error}") from error


def load_schemes() -> dict[str, dict]:
    schemes = {}
    for path in sorted(SCHEMES_DIR.glob("*.toml")):
        slug = path.stem
        data = load_toml(path)
        name = data.get("name")
        colors = data.get("colors")
        if not isinstance(name, str) or not name.strip():
            raise ValueError(f"{path.relative_to(ROOT)} must define a non-empty name")
        if not isinstance(colors, dict):
            raise ValueError(f"{path.relative_to(ROOT)} must define a [colors] table")

        missing = set(REQUIRED_COLORS) - colors.keys()
        unknown = colors.keys() - set(REQUIRED_COLORS)
        if missing:
            raise ValueError(f"{path.relative_to(ROOT)} is missing: {', '.join(sorted(missing))}")
        if unknown:
            raise ValueError(f"{path.relative_to(ROOT)} has unknown colors: {', '.join(sorted(unknown))}")
        for role, value in colors.items():
            if not isinstance(value, str) or not re.fullmatch(r"[0-9a-fA-F]{6}", value):
                raise ValueError(f"{path.relative_to(ROOT)}: {role} must be six hexadecimal digits")

        schemes[slug] = {
            "name": name.strip(),
            "colors": {role: colors[role].lower() for role in REQUIRED_COLORS},
            "path": path,
        }

    if not schemes:
        raise ValueError(f"no schemes found under {SCHEMES_DIR.relative_to(ROOT)}")
    return schemes


def load_selected_scheme(schemes: dict[str, dict]) -> str:
    data = load_toml(CONFIG_PATH)
    selected = data.get("scheme")
    if not isinstance(selected, str) or selected not in schemes:
        raise ValueError(f"{CONFIG_PATH.relative_to(ROOT)} selects unknown scheme {selected!r}")
    return selected


def choose_scheme(schemes: dict[str, dict], selected: str) -> str:
    slugs = sorted(schemes, key=lambda slug: schemes[slug]["name"].casefold())
    current = slugs.index(selected) + 1
    print("Available color schemes:")
    for index, slug in enumerate(slugs, start=1):
        marker = " (active)" if slug == selected else ""
        print(f"  {index}. {schemes[slug]['name']}{marker}")

    try:
        answer = input(f"Select scheme [{current}]: ").strip()
    except (EOFError, KeyboardInterrupt):
        print("\nSelection cancelled.", file=sys.stderr)
        raise SystemExit(1)
    if not answer:
        return selected
    if not answer.isdigit() or not 1 <= int(answer) <= len(slugs):
        raise ValueError(f"selection must be a number from 1 to {len(slugs)}")
    return slugs[int(answer) - 1]


def rgb(hex_color: str) -> tuple[int, int, int]:
    return (
        int(hex_color[0:2], 16),
        int(hex_color[2:4], 16),
        int(hex_color[4:6], 16),
    )


def css_palette(header: str, colors: dict[str, str]) -> str:
    definitions = "\n".join(f"@define-color {role} #{colors[role]};" for role in REQUIRED_COLORS)
    return f"{header}\n{definitions}\n"


def render_outputs(slug: str, scheme: dict) -> dict[Path, str]:
    colors = scheme["colors"]
    source = scheme["path"].relative_to(ROOT)
    css_header = f"/* Generated by scripts/generate_theme.py from {source}. Do not edit. */"
    conf_header = f"# Generated by scripts/generate_theme.py from {source}. Do not edit."
    lua_header = f"-- Generated by scripts/generate_theme.py from {source}. Do not edit."

    lua_values = "\n".join(f'    {role} = "{colors[role]}",' for role in REQUIRED_COLORS)
    hypr_lua = f"{lua_header}\nreturn {{\n{lua_values}\n}}\n"

    def rgb_text(role: str) -> str:
        return ", ".join(str(channel) for channel in rgb(colors[role]))

    hyprlock = f"""{conf_header}
$theme_accent = rgba({colors['accent']}ee)
$theme_accent_bright = rgba({colors['accent_bright']}ee)
$theme_success = rgba({rgb_text('success')}, 0.95)
$theme_error = rgba({rgb_text('error')}, 0.95)
$theme_error_alt = rgba({rgb_text('error_alt')}, 0.95)
$theme_surface_secondary = rgba({rgb_text('surface_secondary')}, 0.72)
$theme_text = rgb({rgb_text('text')})
$theme_text_clock = rgba({rgb_text('text')}, 0.86)
$theme_text_media = rgba({rgb_text('text')}, 0.78)
"""

    swaync = f"""{css_header}
:root {{
    --cc-bg: rgba({rgb_text('surface')}, 0.95);
    --noti-border-color: rgba({rgb_text('accent')}, 0.22);
    --noti-bg: {rgb_text('surface_secondary')};
    --noti-bg-alpha: 0.92;
    --noti-bg-darker: rgb({rgb_text('surface')});
    --noti-bg-hover: rgb({rgb_text('border_muted')});
    --noti-bg-focus: rgba({rgb_text('border_muted')}, 0.65);
    --noti-close-bg: rgb({rgb_text('border_muted')});
    --noti-close-bg-hover: rgb({rgb_text('accent')});
    --text-color: rgb({rgb_text('text')});
    --text-color-disabled: rgb({rgb_text('text_muted')});
    --bg-selected: rgb({rgb_text('accent')});
    --mpris-album-art-overlay: rgba({rgb_text('surface')}, 0.75);
    --mpris-button-hover: rgba({rgb_text('accent_bright')}, 0.35);
}}

{css_palette('', colors).lstrip()}
@define-color panel_bg alpha(@surface, 0.88);
@define-color surface_hover alpha(@surface_secondary, 0.95);
@define-color notification_border alpha(@accent, 0.15);
@define-color mpris_album_art_overlay alpha(@surface, 0.75);
@define-color mpris_button_hover alpha(@accent_bright, 0.35);
@define-color background @surface;
@define-color foreground @text;
@define-color color4 @accent;
@define-color color7 @text;
@define-color color9 @accent;
@define-color bg @panel_bg;
@define-color bg-hover @surface_hover;
@define-color mycolor @accent;
@define-color border-color @notification_border;
@define-color mpris-album-art-overlay @mpris_album_art_overlay;
@define-color mpris-button-hover @mpris_button_hover;
"""

    waybar = f"""{css_palette(css_header, colors)}
@define-color background @surface;
@define-color foreground @text;
@define-color color1 @accent;
@define-color color2 @border_muted;
@define-color color7 @text;
@define-color color9 @accent;
"""

    wofi = f"""{css_palette(css_header, colors)}
@define-color background @surface;
"""

    return {
        CONFIG_PATH: f'scheme = "{slug}"\n',
        OUTPUT_PATHS["hypr_lua"]: hypr_lua,
        OUTPUT_PATHS["hyprlock"]: hyprlock,
        OUTPUT_PATHS["waybar"]: waybar,
        OUTPUT_PATHS["swaync"]: swaync,
        OUTPUT_PATHS["wofi"]: wofi,
    }


def check_outputs(outputs: dict[Path, str]) -> bool:
    stale = []
    for path, expected in outputs.items():
        try:
            actual = path.read_text(encoding="utf-8")
        except OSError:
            actual = None
        if actual != expected:
            stale.append(path.relative_to(ROOT))
    if stale:
        print("Theme outputs are stale or missing:", file=sys.stderr)
        for path in stale:
            print(f"  {path}", file=sys.stderr)
        return False
    print("Theme outputs are current.")
    return True


def write_outputs(outputs: dict[Path, str]) -> None:
    temporary_files = []
    try:
        for path, content in outputs.items():
            try:
                if path.read_text(encoding="utf-8") == content:
                    continue
            except OSError:
                pass
            with tempfile.NamedTemporaryFile(
                mode="w", encoding="utf-8", dir=path.parent, prefix=f".{path.name}.", delete=False
            ) as temporary:
                temporary.write(content)
                temporary.flush()
                os.fsync(temporary.fileno())
                temporary_path = Path(temporary.name)
            temporary_path.chmod(0o644)
            temporary_files.append((temporary_path, path))
        for temporary_path, path in temporary_files:
            os.replace(temporary_path, path)
    finally:
        for temporary_path, _ in temporary_files:
            temporary_path.unlink(missing_ok=True)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    action = parser.add_mutually_exclusive_group()
    action.add_argument("--scheme", metavar="NAME", help="select a scheme without prompting")
    action.add_argument("--list", action="store_true", help="list available schemes")
    action.add_argument("--check", action="store_true", help="check generated files for the active scheme")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    try:
        schemes = load_schemes()
        selected = load_selected_scheme(schemes)
        if args.list:
            for slug in sorted(schemes):
                marker = " *" if slug == selected else ""
                print(f"{slug}\t{schemes[slug]['name']}{marker}")
            return 0
        if args.scheme:
            if args.scheme not in schemes:
                choices = ", ".join(sorted(schemes))
                raise ValueError(f"unknown scheme {args.scheme!r}; choose from: {choices}")
            selected = args.scheme
        elif not args.check:
            selected = choose_scheme(schemes, selected)

        outputs = render_outputs(selected, schemes[selected])
        if args.check:
            return 0 if check_outputs(outputs) else 1
        write_outputs(outputs)
        print(f"Applied {schemes[selected]['name']} ({selected}).")
        return 0
    except ValueError as error:
        print(f"error: {error}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
